name: Bug
description: Reporte de bug
labels: ["bug"]
body:
  - type: textarea
    id: steps
    attributes: { label: Pasos para reproducir }
    validations: { required: true }
  - type: textarea
    id: expected
    attributes: { label: Comportamiento esperado }
  - type: textarea
    id: evidence
    attributes: { label: Evidencia (logs) }
